<?php

namespace Database\Seeders;

use App\Enums\Inventory\BottleState;
use App\Enums\Inventory\LocationStatus;
use App\Enums\Inventory\LocationType;
use App\Models\Inventory\Location;
use App\Models\Inventory\SerializedBottle;
use App\Models\User;
use App\Services\Inventory\MovementService;
use Illuminate\Database\Seeder;

/**
 * InventoryMovementSeeder - Creates explicit inventory movements via MovementService.
 *
 * Most movements are auto-generated by other service calls:
 * - MovementService::breakCase() creates break movements (from InventoryCaseSeeder)
 * - MovementService::recordDestruction/Missing/Consumption() create terminal movements (from SerializedBottleSeeder)
 *
 * This seeder only creates movements that represent explicit operator actions:
 * - transferBottle() for inter-warehouse transfers
 * - placeBottleInConsignment() for consignment placements
 */
class InventoryMovementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $movementService = app(MovementService::class);

        $locations = Location::where('status', LocationStatus::Active)->get();

        if ($locations->isEmpty()) {
            $this->command->warn('No active locations found. Run LocationSeeder first.');

            return;
        }

        $admin = User::first();

        // Get bottles that are currently Stored (available for transfer/consignment)
        $storedBottles = SerializedBottle::where('state', BottleState::Stored)
            ->inRandomOrder()
            ->limit(50)
            ->get();

        if ($storedBottles->isEmpty()) {
            $this->command->warn('No stored bottles found. Run SerializedBottleSeeder first.');

            return;
        }

        // Separate locations by type
        $warehouses = $locations->whereIn('location_type', [LocationType::MainWarehouse, LocationType::SatelliteWarehouse]);
        $consigneeLocations = $locations->where('location_type', LocationType::Consignee);

        $totalCreated = 0;

        // =========================================================================
        // 1. INTERNAL TRANSFERS via MovementService::transferBottle()
        // =========================================================================
        if ($warehouses->count() >= 2) {
            $transferBottles = $storedBottles->take(20);

            $transferReasons = [
                'Rebalancing inventory across locations',
                'Consolidation for efficiency',
                'Temperature-controlled storage requirement',
                'Preparing for upcoming demand',
                'Customer proximity optimization',
                'Pre-positioning for fulfillment',
            ];

            foreach ($transferBottles as $bottle) {
                // Pick a different warehouse as destination
                $destination = $warehouses->where('id', '!=', $bottle->current_location_id)->first();
                if (! $destination) {
                    $destination = $warehouses->random();
                }

                try {
                    $movementService->transferBottle(
                        $bottle,
                        $destination,
                        $admin,
                        fake()->randomElement($transferReasons),
                        fake()->boolean(40) ? 'WMS-TRF-'.fake()->regexify('[A-Z0-9]{10}') : null
                    );
                    $totalCreated++;
                } catch (\Throwable $e) {
                    $this->command->warn("Transfer failed for bottle {$bottle->id}: {$e->getMessage()}");
                }
            }
        }

        // =========================================================================
        // 2. CONSIGNMENT PLACEMENTS via MovementService::placeBottleInConsignment()
        // =========================================================================
        if ($consigneeLocations->isNotEmpty()) {
            // Use remaining bottles not used in transfers
            $consignmentBottles = $storedBottles->skip(20)->take(10);

            $consignmentReasons = [
                'Partner restaurant display inventory',
                'Wine club exclusive allocation',
                'Retailer consignment stock',
                'Hotel cellar program',
                'Private client storage at partner facility',
            ];

            foreach ($consignmentBottles as $bottle) {
                $consigneeLocation = $consigneeLocations->random();

                try {
                    $movementService->placeBottleInConsignment(
                        $bottle,
                        $consigneeLocation,
                        $admin,
                        fake()->randomElement($consignmentReasons)
                    );
                    $totalCreated++;
                } catch (\Throwable $e) {
                    $this->command->warn("Consignment failed for bottle {$bottle->id}: {$e->getMessage()}");
                }
            }
        }

        $this->command->info("Created {$totalCreated} explicit inventory movements via MovementService.");
    }
}
