<?php

namespace App\Models\Commercial;

use App\Enums\Commercial\PriceSource;
use App\Models\Pim\SellableSku;
use App\Traits\HasUuid;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * PriceBookEntry Model
 *
 * Represents an individual price entry within a Price Book,
 * linking a Sellable SKU to its base price.
 *
 * @property string $id
 * @property string $price_book_id
 * @property string $sellable_sku_id
 * @property string $base_price
 * @property PriceSource $source
 * @property string|null $policy_id
 */
class PriceBookEntry extends Model
{
    use HasFactory;
    use HasUuid;

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'price_book_entries';

    /**
     * The attributes that are mass assignable.
     *
     * @var list<string>
     */
    protected $fillable = [
        'price_book_id',
        'sellable_sku_id',
        'base_price',
        'source',
        'policy_id',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'source' => PriceSource::class,
            'base_price' => 'decimal:2',
        ];
    }

    /**
     * Get the price book that this entry belongs to.
     *
     * @return BelongsTo<PriceBook, $this>
     */
    public function priceBook(): BelongsTo
    {
        return $this->belongsTo(PriceBook::class);
    }

    /**
     * Get the sellable SKU that this entry prices.
     *
     * @return BelongsTo<SellableSku, $this>
     */
    public function sellableSku(): BelongsTo
    {
        return $this->belongsTo(SellableSku::class);
    }

    /**
     * Get the pricing policy that generated this entry (if policy-generated).
     * Note: Returns a BelongsTo relationship that will resolve when PricingPolicy is created in US-020.
     *
     * @return BelongsTo<\Illuminate\Database\Eloquent\Model, $this>
     */
    public function pricingPolicy(): BelongsTo
    {
        // PricingPolicy model will be created in US-020
        // Using string-based class reference to avoid compile-time errors
        // @phpstan-ignore argument.type (PricingPolicy model does not exist yet)
        return $this->belongsTo('App\Models\Commercial\PricingPolicy', 'policy_id');
    }

    /**
     * Check if this entry was manually set.
     */
    public function isManual(): bool
    {
        return $this->source === PriceSource::Manual;
    }

    /**
     * Check if this entry was generated by a pricing policy.
     */
    public function isPolicyGenerated(): bool
    {
        return $this->source === PriceSource::PolicyGenerated;
    }

    /**
     * Get the source label for UI display.
     */
    public function getSourceLabel(): string
    {
        return $this->source->label();
    }

    /**
     * Get the source color for UI display.
     */
    public function getSourceColor(): string
    {
        return $this->source->color();
    }
}
