<?php

namespace App\Enums\Finance;

/**
 * Enum SubscriptionPlanType
 *
 * The type of subscription plan.
 */
enum SubscriptionPlanType: string
{
    case Membership = 'membership';
    case Service = 'service';

    /**
     * Get the human-readable label for this type.
     */
    public function label(): string
    {
        return match ($this) {
            self::Membership => 'Membership',
            self::Service => 'Service',
        };
    }

    /**
     * Get the color for UI display (Filament-compatible).
     */
    public function color(): string
    {
        return match ($this) {
            self::Membership => 'primary',
            self::Service => 'info',
        };
    }

    /**
     * Get the icon for UI display (Filament-compatible).
     */
    public function icon(): string
    {
        return match ($this) {
            self::Membership => 'heroicon-o-user-group',
            self::Service => 'heroicon-o-cog-6-tooth',
        };
    }

    /**
     * Get the invoice type generated by this subscription plan.
     */
    public function invoiceType(): InvoiceType
    {
        return InvoiceType::MembershipService;
    }
}
